#!/usr/bin/env python3
"""
find_skill.py: scoped skill search for the Number Pii toolkit.

Searches `Teams/skills/skills-index.json` (generated by
`scripts/build_skills_index.py`; filesystem fallback when missing) and prints
matching skill rows only, without loading any full `SKILL.md`. The AI
assistant picks the right skill from the short result list before spending
tokens to load its full definition.

Tiers gate what surfaces: by default only `curated` skills (human-reviewed,
referenced by role files) are shown, with a one-line count of hidden matches.
`--all` widens to the standard tier; archived skills only appear with
`--tier archive`. Canonical skills sort first inside their tier.

Usage:
    python3 scripts/find_skill.py <keyword>               # curated matches + hidden count
    python3 scripts/find_skill.py --all <keyword>         # include unreviewed (standard) skills
    python3 scripts/find_skill.py --tier standard <kw>    # a single tier only
    python3 scripts/find_skill.py --domain <name>         # list a domain (curated by default)
    python3 scripts/find_skill.py --list-domains          # print the domain index

Arguments:
    keyword          Case-insensitive substring matched against names AND summaries
    --domain, -d     Restrict results to a domain (case-insensitive partial match)
    --tier           Restrict to one tier: curated, standard, or archive
    --all            Search curated and standard tiers together
    --list-domains   Print every domain and exit
    --names-only     Output skill names only; useful for piping

Examples:
    python3 scripts/find_skill.py testing
    python3 scripts/find_skill.py --all rag
    python3 scripts/find_skill.py --domain security --all
    python3 scripts/find_skill.py --names-only react | head
"""

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from lib.frontmatter import parse_frontmatter  # noqa: E402

ROOT = HERE.parent
SKILLS_DIR = ROOT / "Teams" / "skills"
INDEX_FILE = SKILLS_DIR / "skills-index.json"

UNCATEGORISED = "uncategorised"
TIER_RANK = {"curated": 1, "standard": 2, "archive": 3}


def load_index() -> list[dict]:
    """Load skills-index.json, falling back to a live frontmatter scan."""
    if INDEX_FILE.exists():
        try:
            return json.loads(INDEX_FILE.read_text(encoding="utf-8"))["skills"]
        except (json.JSONDecodeError, KeyError):
            pass  # fall through to the scan
    skills = []
    if not SKILLS_DIR.exists():
        return skills
    for folder in sorted(SKILLS_DIR.iterdir()):
        if not folder.is_dir() or folder.name.startswith((".", "_")):
            continue
        fm, _ = parse_frontmatter(folder / "SKILL.md")
        skills.append({
            "name": folder.name,
            "domain": fm.get("domain") if isinstance(fm.get("domain"), str) else UNCATEGORISED,
            "summary": fm.get("summary") if isinstance(fm.get("summary"), str) else "",
            "tier": fm.get("tier") if fm.get("tier") in TIER_RANK else "standard",
            "canonical": fm.get("canonical") == "true",
        })
    return skills


def matches(skill: dict, query: str) -> bool:
    q = query.lower().strip()
    return q in skill["name"].lower() or q in (skill.get("summary") or "").lower()


def filter_skills(skills: list[dict], keyword: str | None, domain: str | None,
                  tiers: set[str]) -> tuple[list[dict], int]:
    """Return (visible matches sorted for display, hidden match count).

    Hidden matches are ones excluded only by the tier filter; the count lets
    the caller hint that --all or --tier would widen the search.
    """
    pool = skills
    if domain:
        d = domain.lower().strip()
        pool = [s for s in pool if d in (s.get("domain") or "").lower()]
    if keyword:
        pool = [s for s in pool if matches(s, keyword)]

    visible = [s for s in pool if s.get("tier", "standard") in tiers]
    hidden = len(pool) - len(visible)
    visible.sort(key=lambda s: (0 if s.get("canonical") else 1,
                                TIER_RANK.get(s.get("tier", "standard"), 2),
                                s["name"]))
    return visible, hidden


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Search skills without loading any SKILL.md.",
        epilog="Reads Teams/skills/skills-index.json; falls back to scanning frontmatter.",
    )
    parser.add_argument("keyword", nargs="?", help="Substring matched in names and summaries")
    parser.add_argument("--domain", "-d", help="Restrict to a domain (partial match)")
    parser.add_argument("--tier", choices=sorted(TIER_RANK),
                        help="Restrict to one tier (archive is only visible this way or via --all)")
    parser.add_argument("--all", action="store_true",
                        help="Include every tier, not just curated")
    parser.add_argument("--list-domains", action="store_true",
                        help="List all domains and exit")
    parser.add_argument("--names-only", action="store_true",
                        help="Print skill names only (no domain/summary suffix)")
    args = parser.parse_args()

    skills = load_index()
    if not skills:
        print(f"No skills found. Check {SKILLS_DIR} exists.", file=sys.stderr)
        return 1

    if args.list_domains:
        domains: dict[str, int] = {}
        for s in skills:
            if s.get("tier") != "archive":
                domains[s.get("domain") or UNCATEGORISED] = domains.get(s.get("domain") or UNCATEGORISED, 0) + 1
        for name in sorted(domains, key=str.lower):
            print(f"{name}  ({domains[name]} skills)")
        return 0

    if args.tier:
        tiers = {args.tier}
    elif args.all:
        tiers = set(TIER_RANK)
    else:
        tiers = {"curated"}

    visible, hidden = filter_skills(skills, args.keyword, args.domain, tiers)

    if not visible:
        if hidden:
            print(f"No curated matches; {hidden} match(es) in other tiers. "
                  "Re-run with --all or --tier.", file=sys.stderr)
        else:
            print("No matches.", file=sys.stderr)
        return 1

    for s in visible:
        if args.names_only:
            print(s["name"])
            continue
        marks = []
        if s.get("canonical"):
            marks.append("canonical")
        if s.get("tier") and s["tier"] != "curated":
            marks.append(s["tier"])
        suffix = f" ({', '.join(marks)})" if marks else ""
        summary = s.get("summary") or ""
        line = f"{s['name']}  [{s.get('domain') or UNCATEGORISED}]{suffix}"
        if summary:
            line += f"  : {summary}"
        print(line)

    if hidden and not args.names_only:
        print(f"\n{hidden} more match(es) in tiers outside this search; "
              "use --all or --tier to include them.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
